### ISSUE TITLE
Table uses grid-column: 2 on everything

### ISSUE THREAD

**Issue by ryelo** [RedHatInsights/insights-frontend-components#151]
https://github.com/RedHatInsights/insights-frontend-components/blob/6706bda4535c0139932f91e16088bfc689105a5a/src/PresentationalComponents/Table/Table/styles.scss#L230

This is really messing things up when trying to put in a progress bar. Is there a need for this? It seems to only affect if there is a `<div>` inside the `<td>`

**Comment by ryelo** [comment]
@karelhala @AllenBW Thoughts?

**Comment by karelhala** [comment]
This styling is taken out from @mattnolting PR. However better approach would be to remove these stylings and use PF4's one. Don't know if this will solve it tho.

**Comment by ryelo** [comment]
I think using their styling would probably be a good idea anyway, unless (@karelhala) your table is closed to being merged in react

**Comment by AllenBW** [comment]
<img width="1398" alt="screen shot 2018-11-20 at 10 20 35 am" src="https://user-images.githubusercontent.com/6640236/48783282-00ff5c00-ecae-11e8-8202-c18cfd989392.png">

Ditto using pf4 styling, but also, it doesn't removing this doesn't appear to jack anything up (unless imma looking in the wrong place)

**Comment by karelhala** [comment]
@ryelo I'll update our table comp with newest styling, we don't know how much time it'll take for PF to merge the table PR.
