### ISSUE TITLE
Cannot import CSS for Dropdown

### ISSUE THREAD

**Issue by dLobatog** [RedHatInsights/insights-frontend-components#172]
According to https://github.com/RedHatInsights/insights-frontend-components/blob/master/doc/components/dropdown.md I should be importing a CSS file for Dropdown. I don't think that css file is available anymore, but even importing the CSS like it did, `@import '~@patternfly/patternfly-next/components/Dropdown/styles.scss';`, I get quite an odd button:

![screenshot from 2018-12-17 10-07-56](https://user-images.githubusercontent.com/598891/50077093-b0631c00-01e3-11e9-854e-4de8575ce41b.png)
![screenshot from 2018-12-17 10-11-13](https://user-images.githubusercontent.com/598891/50077256-2ff0eb00-01e4-11e9-8227-72bf13df868d.png)

Notice the icon has no left padding, it's the same if I write some text instead of the icon, and the `DropdownItem`s seem to render in a strange way.

**Comment by ryelo** [comment]
@dLobatog Try using https://patternfly-react.surge.sh/patternfly-4/components/dropdown

**Comment by ryelo** [comment]
@dLobatog any other issues with this or can I close?
