### ISSUE TITLE
Inventory should not show all systems when items=[]

### ISSUE THREAD

**Issue by jiridostal** [RedHatInsights/insights-frontend-components#184]
When providing "items" parameter, empty array should not be treated as "show all". It should show empty table instead or some kind of message that tells the user that there are no systems to be listed. ie. Vulnerability -> CVE -> affected systems table.

**Comment by karelhala** [comment]
Is happening again because of when we moved to new version of table and needs re visit.

**Comment by karelhala** [comment]
This should already be fixed am I right @jiridostal

**Comment by jiridostal** [comment]
It is, closing. Thanks! :yellow_heart:
