### ISSUE TITLE
Add global variables

### ISSUE THREAD

**Issue by ryelo** [RedHatInsights/insights-frontend-components#35]
Based on feedback from other teams, they would like a set of global variables to easily reference. We'll just consume Patternfly variables into our own to serve to the apps.

**Comment by ryelo** [comment]
@karelhala What's the best way to publish a `.scss` file? I can put all of the variables + helpers in one file.

**Comment by karelhala** [comment]
We can always copy all `.scss` files to dist as well so consumers can use them as well.

**Comment by ryelo** [comment]
Running list of variables:

```CSS
//Spacing
$ins-padding: $pf-global--space-size-root;
$ins-margin: $pf-global--spacer--xl;
$ins-gutter: $pf-global--gutter;

// Font Size
$ins-fontSize: $pf-global--font-size-root;
$ins-fontSize--sm: $pf-global--FontSize--sm;
$ins-fontSize--xl: $pf-global--FontSize--xl;

// Borders
$ins-borderRadius: $pf-global--BorderRadius--sm;
$ins-borderRadius--round: $pf-global--BorderRadius--lg;

// Grid breakpoints
$ins-break--xs: $pf-global--breakpoint--xs;
$ins-break--sm: $pf-global--breakpoint--sm;
$ins-break--md: $pf-global--breakpoint--md;
$ins-break--lg: $pf-global--breakpoint--lg;
$ins-break--xl: $pf-global--breakpoint--xl;

// Colors
```

**Comment by karelhala** [comment]
@ryelo https://github.com/RedHatInsights/insights-frontend-components/pull/42 once this is merged you can start writing these variables
